---
name: {{ cookiecutter.project_slug }}-job-toml-lint
{% raw %}
on:
  workflow_call:
    inputs:
      VERBOSITY:
        description: "Manages the types of Slack notifications."
        required: true
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_tomll:

    runs-on: ubuntu-latest

    steps:
      - name: Toml Lint Test -- Checkout Repository
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_CHECKOUT }}{% raw %}

      - name: Toml Lint Test -- Setup Environment
        run: |
          source "./.github/scripts/workflow-setup-environment.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Toml Lint Test -- Install Linter
        run: |
          sudo apt-get install -y golang-github-pelletier-go-toml
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Toml Lint Test -- Run Linter
        run: |
          find . -type f -name "*.toml" -exec tomll "{}" \;
          git diff --exit-code

      - name: Toml Lint Test -- Report Job Status (Success)
        if: inputs.VERBOSITY == true
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: toml linting was successful!"

      - name: Toml Lint Test -- Report Job Status (Failure)
        if: failure()
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: toml linting has failed!"
{% endraw %}