---
name: {{ cookiecutter.project_slug }}-github-workflow-push

# This workflow is configured by values found in the .github/config/workflows/workflow-push.json file.
# It's encouraged to explore the configuration before customizing this file.
# This will allow you to upgrade to future versions of this template without complications.

# For further details please consult the documentation here:
# https://github.com/niall-byrne/ansible-workbench

on:
  push:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false
#    GALAXY_API_KEY:
#      description: "Optional, enables importing the role into Ansible Galaxy."
#      required: false

jobs:

  configuration:

    runs-on: ubuntu-latest
    outputs:
      configuration: {% raw %}${{ steps.configuration.outputs.value }}{% endraw %}
      molecule-scenarios: {% raw %}${{ steps.molecule-scenarios.outputs.value }}{% endraw %}

    steps:
      - name: Create Configuration -- Checkout Repository
        uses: {{ cookiecutter._GITHUB_ACTION_CHECKOUT }}

      - name: Create Configuration -- Validate the 'workflow-push.json' File
        run: |
          python -m json.tool "./.github/config/workflows/workflow-push.json" >> /dev/null

      - name: Create Configuration -- Set the Active Molecule Test Scenarios as Output
        id: molecule-scenarios
        run: |
          source "./.github/scripts/workflow-identify-molecule-scenarios.sh"

      - name: Create Configuration -- Set the 'workflow-push.json' Configuration File as Output
        id: configuration
        run: |
          source "./.github/scripts/workflow-set-value.sh" cat "./.github/config/workflows/workflow-push.json"
