---
name: {{ cookiecutter.project_slug }}-job-security
{% raw %}
on:
  workflow_call:
    inputs:
      TRUFFLEHOG_ARGS:
        description: "Extra arguments to pass to the trufflehog binary."
        required: true
        type: string
      VERBOSITY:
        description: "Manages the types of Slack notifications."
        required: true
        type: boolean
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

jobs:

  run_trufflehog:

    runs-on: ubuntu-latest

    steps:
      - name: Security Test Repo -- Checkout Repository
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_CHECKOUT }}{% raw %}
        with:
          fetch-depth: 0

      - name: Security Test Repo -- Setup Environment
        run: |
          source "./.github/scripts/workflow-setup-environment.sh"
          source "./.github/scripts/workflow-determine-pushed-commits.sh"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Security Test -- Run Trufflehog
        uses: {% endraw %}{{ cookiecutter._GITHUB_ACTION_TRUFFLEHOG }}{% raw %}
        with:
          base: ${{ env.PUSHED_COMMIT_START }}
          extra_args: ${{ inputs.TRUFFLEHOG_ARGS }}
          head: ${{ env.BRANCH_OR_TAG }}
          path: .

      - name: Security Test Repo -- Report Job Status on Success
        if: inputs.VERBOSITY == true
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":white_check_mark: security checks succeeded!"

      - name: Security Test Repo -- Report Job Status on Failure
        if: failure()
        run: |
          "./.github/scripts/task-slack-notification.sh" "${NOTIFICATION}" ":x: security checks failed!"
{% endraw %}